require: rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"

  NewCops: enable

############ Layout ############

Layout/LineLength:
  Max: 130
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

############ Metrics ############

Metrics/BlockLength:
  Exclude:
    - "spec/**/*" # RSpecは1つのブロックあたりの行数が多くなるため、チェックの除外から外す
    - "config/environments/*.rb"

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

############ Style ############

Style/StringLiterals:
  EnforcedStyle: double_quotes # 自動生成されるファイルが比較的ダブルクォートのイメージがあるため

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

############ Rails ############

Rails:
  Enabled: true

Rails/PluckId:
  Enabled: false

Rails/TableNameAssignment:
  Enabled: false